In [1]:
import pandas as pd
from ehull_utils import collect_mlip_energies_to_df, construct_phase_diagrams
import os
from pymatgen.core import Structure

In [2]:
hdp_df = pd.read_csv("/home/lwalterb/hdp_project/HDP_WorkFlow_Analysis/E_above_hull/HDP_CombinedInfo_WithChemSys.csv")
hdp_df.set_index('comp',inplace=True)
mlip_df = pd.read_csv("/home/lwalterb/hdp_project/HDP_WorkFlow_Analysis/E_above_hull/hdp_mlipenergies_full.csv",index_col=0)
mlip_df['structure'] = mlip_df.apply(lambda row: Structure.from_dict(eval(row['structure_dict'])),axis=1)

In [3]:
ehull_df, eform_df = construct_phase_diagrams(
    hdp_df= hdp_df,
    subsys_MLIPenergy_df= mlip_df,
    dataframe_savedir= None,
    phasediagram_savedir= None
)

In [10]:
ehull_df

               MACE-MPA-0  MACE-MP-0b3  MatPES-r2SCAN  SevenNet
1000_CsAgLuCl    0.000000     0.000000       0.000000  0.000000
1001_CsAuVCl     0.146274     0.127443       0.113728  0.152083
1002_CsNaPrCl    0.000000     0.001293       0.000000  0.000000
1003_CsAgDyCl    0.000000     0.000000       0.000000  0.000000
1004_CsMgNdCl    0.118294     0.000000       0.000000  0.023339
...                   ...          ...            ...       ...
3750_CsCsAuF     0.055910     0.049155       0.084570  0.057368
3751_CsCsAuCl    0.139114     0.124520       0.111744  0.135984
3752_CsCsTlF     0.000009     0.000000       0.000000  0.000000
3754_CsCsNpF     0.000000     0.000000       0.054231  0.000000
3756_CsCsAmF          NaN          NaN            NaN       NaN

[2542 rows x 4 columns]

In [3]:
diagram_dir = 'MLIP_PhaseDiagrams_20250720'
os.makedirs(diagram_dir,exist_ok=True)

In [ ]:
ehull_df = get_e_above_hull_df(hdp_df,mlip_df,diagram_output_dir=None)

                         MACE-MPA-0                           MACE-MP-0b3  \
              E_above_hull_per_atom E_form_per_atom E_above_hull_per_atom
1000_CsAgLuCl              0.000000       -1.861481              0.000000
1001_CsAuVCl               0.146274       -1.281205              0.127443
1002_CsNaPrCl              0.000000       -2.116031              0.001293
1003_CsAgDyCl              0.000000       -1.860123              0.000000
1004_CsMgNdCl              0.118294       -1.910491              0.000000

                                      MatPES-r2SCAN                  \
              E_form_per_atom E_above_hull_per_atom E_form_per_atom
1000_CsAgLuCl       -1.850720              0.000000       -2.124572
1001_CsAuVCl        -1.289001              0.113728       -1.577343
1002_CsNaPrCl       -2.110716              0.000000       -2.392588
1003_CsAgDyCl       -1.853998              0.000000       -2.064005
1004_CsMgNdCl       -2.075359              0.000000       -2.417246

                           SevenNet
              E_above_hull_per_atom E_form_per_atom
1000_CsAgLuCl              0.000000       -1.868575
1001_CsAuVCl               0.152083       -1.296619
1002_CsNaPrCl              0.000000       -2.129687
1003_CsAgDyCl              0.000000       -1.873152
1004_CsMgNdCl              0.023339       -2.017622

In [13]:
ehull_df = ehull_df.round(4)
ehull_df.to_csv(f"{diagram_dir}/HDP_EHull_EForm_overview.csv")
d_ehull = ehull_df.xs('E_above_hull_per_atom',axis=1,level=1)
d_ehull.to_csv(f"{diagram_dir}/HDP_EHull_4MLIP.csv")
d_eform = ehull_df.xs('E_form_per_atom',axis=1,level=1)
d_eform.to_csv(f"{diagram_dir}/HDP_EForm_4MLIP.csv")

In [9]:
d_ehull = ehull_df.round(4)
print('MLIP:','\t','NaN vals:', '\t', 'share unstable:')

for mlip in d_ehull.columns:
    sclean = d_ehull[mlip].dropna()
    dropped_cols = len(d_ehull) - len(sclean)
    non_stalbe = sclean[sclean>=0.1]
    print(mlip, '\t', dropped_cols, '\t', len(non_stalbe)/len(sclean))

MLIP: 	 NaN vals: 	 share unstable:
MACE-MPA-0 	 256 	 0.27340332458442695
MACE-MP-0b3 	 257 	 0.21312910284463896
MatPES-r2SCAN 	 258 	 0.16856392294220665
SevenNet 	 256 	 0.23622047244094488

In [14]:
print('MLIP:', '\t','NaN vals:')
for mlip in [x for x in mlip_df.columns if x.startswith('E_')]:
    all_ens = mlip_df[mlip].dropna()
    dropped_comps = len(mlip_df) - len(all_ens)
    print(mlip, '\t', dropped_comps)

MLIP: 	 NaN vals:
E_MACE-MPA-0 	 271
E_MACE-MP-0b3 	 276
E_MatPES-r2SCAN 	 389
E_SevenNet 	 270

In [22]:
d_ehull.dropna(how='all')

               MACE-MPA-0  MACE-MP-0b3  MatPES-r2SCAN  SevenNet
1000_CsAgLuCl      0.0000       0.0000         0.0000    0.0000
1001_CsAuVCl       0.1463       0.1274         0.1137    0.1521
1002_CsNaPrCl      0.0000       0.0013         0.0000    0.0000
1003_CsAgDyCl      0.0000       0.0000         0.0000    0.0000
1004_CsMgNdCl      0.1183       0.0000         0.0000    0.0233
...                   ...          ...            ...       ...
3749_CsCsIrBr      0.0424       0.0622         0.1100    0.0661
3750_CsCsAuF       0.0559       0.0492         0.0846    0.0574
3751_CsCsAuCl      0.1391       0.1245         0.1117    0.1360
3752_CsCsTlF       0.0000       0.0000         0.0000    0.0000
3754_CsCsNpF       0.0000       0.0000         0.0542    0.0000

[2286 rows x 4 columns]

In [24]:
print('MLIP:','\t\t','NaN vals:')
for mlip in mlip_df.columns:
    if not str(mlip).startswith('E_'):
        continue
    sclean = mlip_df[mlip].dropna()
    dropped_cols = len(mlip_df) - len(sclean)
    # non_stalbe = sclean[sclean>0.05]
    print(mlip, '\t\t', dropped_cols)

MLIP: 		 NaN vals:
E_MACE-MPA-0 		 271
E_MACE-MP-0b3 		 276
E_MatPES-r2SCAN 		 389
E_SevenNet 		 270

In [26]:
mlip_df[mlip_df['E_MatPES-r2SCAN'].isna()]

,structure_dict,chemsys,nsites,E_MACE-MPA-0,E_MACE-MP-0b3,E_MatPES-r2SCAN,E_SevenNet,structure
mp-1181390,"{'@module': 'pymatgen.core.structure', '@class...",F-Ga,8,NaN,NaN,NaN,-21.792150,"[[0. 1.3253375 2.506889 ] Ga, [0. 0. 0...."
mp-1110886,"{'@module': 'pymatgen.core.structure', '@class...",Br-Ga-K,10,-29.148709,-29.130527,NaN,-29.163197,"[[8.501715 8.501715 8.501715] K, [2.833905 2.8..."
mp-570796,"{'@module': 'pymatgen.core.structure', '@class...",Cl-Sb,48,-137.828971,-138.415662,NaN,-137.712036,"[[1.72574949 1.55861631 8.24246281] Sb, [ 3.49..."
mp-29671,"{'@module': 'pymatgen.core.structure', '@class...",I-Tm,3,-10.929189,-10.935599,NaN,-10.951619,"[[0. 0. 0.] Tm, [2.04507691 1.18072332 5.71270..."
mp-454,"{'@module': 'pymatgen.core.structure', '@class...",Ga-Na,5,-14.113820,-14.141008,NaN,-14.189062,"[[0. 0. 0.] Na, [0.61914425 2.94032825 1.76222..."
...,...,...,...,...,...,...,...,...
3574_CsNiRaI,"{'@module': 'pymatgen.core.structure', '@class...",Cs-I-Ni-Ra,10,NaN,NaN,NaN,NaN,"[[0. 0. 0.] Ni, [6.05933692 6.05933692 6.05933..."
3581_CsPoVacI,"{'@module': 'pymatgen.core.structure', '@class...",Cs-I-Po,9,NaN,NaN,NaN,NaN,"[[0. 0. 0.] Po, [2.92767613 2.92767613 2.92767..."
3596_CsAmVacI,"{'@module': 'pymatgen.core.structure', '@class...",Am-Cs-I,9,NaN,NaN,NaN,NaN,"[[0. 0. 0.] Am, [2.90610819 2.90610819 2.90610..."
3597_CsCmVacI,"{'@module': 'pymatgen.core.structure', '@class...",Cm-Cs-I,9,NaN,NaN,NaN,NaN,"[[0. 0. 0.] Cm, [2.90516777 2.90516777 2.90516..."
3756_CsCsAmF,"{'@module': 'pymatgen.core.structure', '@class...",Am-Cs-F,10,NaN,NaN,NaN,NaN,"[[0. 0. 0.] Cs, [5.01524121 5.01524121 5.01524..."

In [5]:
example = '1001_CsAuVCl'
subsystems = eval(hdp_df.loc[example]['subsystems'])
pdh, _ = get_single_distance_tohull(
    compID = example,
    subsys_list = subsystems,
    mlip_energies = mlip_df,
)

In [15]:
d_ehull.describe()

        MACE-MPA-0  MACE-MP-0b3  MatPES-r2SCAN     SevenNet
count  2286.000000  2285.000000    2284.000000  2286.000000
mean      0.077237     0.064139       0.052612     0.067739
std       0.094130     0.095521       0.083692     0.087929
min       0.000000     0.000000       0.000000     0.000000
25%       0.005125     0.000000       0.000000     0.000200
50%       0.050500     0.029900       0.018750     0.039600
75%       0.107100     0.087800       0.066425     0.094675
max       0.598500     0.786100       0.630800     0.680000

In [11]:
import numpy as np
np.isnan(hdp_df.loc['1253_CsPoVacCl']['element.B2'])

np.True_

In [ ]:
fig = phd.get_plot()
fig.update_layout(
    height = 600,
    width = 1000,
    plot_bgcolor = "white",
    paper_bgcolor = "white",
)

fig.write_html('pd_test.html')

In [ ]:
dir(phd)

['REDIRECT',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__get_pydantic_core_schema__',
 '__get_pydantic_json_schema__',
 '__get_validators__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__modify_schema__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_compute',
 '_from_dict_legacy',
 '_generic_json_schema',
 '_get_all_facets_and_simplexes',
 '_get_facet_and_simplex',
 '_get_facet_chempots',
 '_get_simplex_intersections',
 '_get_stable_entries_in_space',
 '_qhull_spaces',
 '_stable_entries',
 '_stable_spaces',
 '_validate_monty',
 'all_entries',
 'all_entries_hulldata',
 'as_dict',
 'computed_data',
 'dim',
 'el_refs',
 'elements',
 'entries',
 'facets',
 'formation_energy_tol',
 'from_dict',
 'get_all_chempots',
 'get_chempot_range_map',
 'get_chempot_range_stability_phase',
 'get_composition_chempots',
 'get_critical_compositions',
 'get_decomp_and_e_above_hull',
 'get_decomp_and_hull_energy_per_atom',
 'get_decomp_and_phase_separation_energy',
 'get_decomposition',
 'get_e_above_hull',
 'get_element_profile',
 'get_equilibrium_reaction_energy',
 'get_form_energy',
 'get_form_energy_per_atom',
 'get_hull_energy',
 'get_hull_energy_per_atom',
 'get_phase_separation_energy',
 'get_plot',
 'get_reference_energy',
 'get_reference_energy_per_atom',
 'get_transition_chempots',
 'getmu_vertices_stability_phase',
 'load',
 'numerical_tol',
 'pd_coords',
 'qhull_data',
 'qhull_entries',
 'save',
 'simplexes',
 'stable_entries',
 'to_json',
 'unsafe_hash',
 'unstable_entries',
 'validate_monty_v1',
 'validate_monty_v2']

In [ ]:
phd.get_all_chempots(mlip_df.loc[example]['structure'].composition)

{'mp-1206014-mp-28117-mp-541656-mp-1008634': {Element Cs: np.float64(-29.38341999053955),
  Element Au: np.float64(-50.58261489868164),
  Element V: np.float64(-18.475229263305657),
  Element Cl: np.float64(-6.701635360717775)},
 'mp-541084-mp-1206014-mp-22865-mp-1008634': {Element Cs: np.float64(-28.288455963134748),
  Element Au: np.float64(-50.58261489868164),
  Element V: np.float64(-17.722114562988224),
  Element Cl: np.float64(-7.1921424865722825)},
 'mp-541084-mp-1206014-mp-28117-mp-1008634': {Element Cs: np.float64(-29.006862640380852),
  Element Au: np.float64(-50.58261489868164),
  Element V: np.float64(-17.72211456298826),
  Element Cl: np.float64(-6.952673594156908)},
 'mp-23484-mp-1206014-mp-541656-mp-1008634': {Element Cs: np.float64(-29.130762100219695),
  Element Au: np.float64(-50.58261489868164),
  Element V: np.float64(-18.98054504394537),
  Element Cl: np.float64(-6.701635360717775)},
 'mp-23484-mp-1206014-mp-22865-mp-1008634': {Element Cs: np.float64(-28.603063583374038),
  Element Au: np.float64(-50.58261489868164),
  Element V: np.float64(-18.980545043945376),
  Element Cl: np.float64(-6.877534866332994)}}

In [29]:
mlip_df.iloc[87]['structure'].composition

Composition('V6 Pb10 F38')

In [ ]:

phd.get_decomp_and_hull_energy_per_atom(mlip_df.loc[example]['structure'].composition)

({PDEntry : Cs2 V1 Cl6 (mp-1206014) with energy = -117.4519: np.float64(0.9000000000000004),
  PDEntry : Au2 (mp-1008634) with energy = -101.1652: np.float64(0.09999999999999998)},
 np.float64(-16.80344963073731))

In [ ]:
my_entrie = [x for x in pd.entries if x.name == example][0]
phd.get_decomp_and_e_above_hull(my_entrie, check_stable=False)

({PDEntry : Cs2 V1 Cl6 (mp-1206014) with energy = -117.4519: np.float64(0.9000000000000004),
  PDEntry : Au2 (mp-1008634) with energy = -101.1652: np.float64(0.09999999999999998)},
 np.float64(0.11372795104980682))

In [43]:
dir(my_entrie.composition)

['REDIRECT',
 'STRING_MODE',
 '__abstractmethods__',
 '__add__',
 '__annotations__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__get_pydantic_core_schema__',
 '__get_pydantic_json_schema__',
 '__get_validators__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__modify_schema__',
 '__module__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '_abc_impl',
 '_comps_from_fuzzy_formula',
 '_data',
 '_generic_json_schema',
 '_get_oxi_state_guesses',
 '_n_atoms',
 '_parse_formula',
 '_validate_monty',
 'add_charges_from_oxi_state_guesses',
 'allow_negative',
 'almost_equals',
 'alphabetical_formula',
 'amount_tolerance',
 'anonymized_formula',
 'as_data_dict',
 'as_dict',
 'as_reduced_dict',
 'as_weight_dict',
 'average_electroneg',
 'charge',
 'charge_balanced',
 'charge_balanced_tolerance',
 'chemical_system',
 'chemical_system_set',
 'contains_element_type',
 'copy',
 'element_composition',
 'elements',
 'formula',
 'fractional_composition',
 'from_dict',
 'from_weight_dict',
 'from_weights',
 'get',
 'get_atomic_fraction',
 'get_el_amt_dict',
 'get_integer_formula_and_factor',
 'get_reduced_composition_and_factor',
 'get_reduced_formula_and_factor',
 'get_wt_fraction',
 'hill_formula',
 'is_element',
 'items',
 'iupac_formula',
 'keys',
 'load',
 'num_atoms',
 'oxi_prob',
 'oxi_state_guesses',
 'ranked_compositions_from_indeterminate_formula',
 'reduced_composition',
 'reduced_formula',
 'remove_charges',
 'replace',
 'save',
 'special_formulas',
 'to_data_dict',
 'to_html_string',
 'to_json',
 'to_latex_string',
 'to_pretty_string',
 'to_reduced_dict',
 'to_unicode_string',
 'to_weight_dict',
 'total_electrons',
 'unsafe_hash',
 'valid',
 'validate_monty_v1',
 'validate_monty_v2',
 'values',
 'weight']